
# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "app building"
  lane :build_app do
	cocoapods(clean_install: true)
	gym
  end
end
